### ISSUE TITLE
Add Fake Boolean

### ISSUE THREAD

**Issue by CodyEngel** [CodyEngel/fakek#26]
Add `fakeBoolean` to `FakeContext`, this will enable easier testing of true/false scenarios.

**Comment by DeMack** [comment]
This sounds interesting. I can tackle it.

**Comment by RafaelPereiraSantos** [comment]
Hi @CodyEngel, I don't know if you heard about it, but from now, hacktoberfest is opt-in so, in order to a pull request be a valid contribution it needs to be submitted to a project with the topic ```hacktoberfest```.

I saw that the project is currently without the topic but it has issues with the label, so i don't know if you are aware about it and i thought that would be a good idea check it with you.

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by CodyEngel** [comment]
Thanks @RafaelPereiraSantos, I heard about the topic requirement and updated the project with that topic. Thank you for the heads up though, I missed the email. This project seems to be getting more traction so I'm going to try to create more issues for Hacktoberfest.
